version: "3.7"
services:
  envoy:
    build:
      context: ./envoy
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "9090:9090"

  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
